# -*- coding: utf-8 -*-
"""2D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beubpl2bRiFiBTOZFkX44swDsKgREf-b
"""

#2D- Geometry
#Q1. Parameter values for y=ax+b
#a = slope of the line passing through two points.
#Slope is also the Tangent of the angle that the line makes with the x-axis.
#b = intercept of the line passing through two points.
import numpy as np
def param_line(x0,y0,x1,y1):
  #If both the x-coordinates are zero, then the line is perpendicular i.e. the line makes an angle of 90 deg with the x-axis.
  if x0 == x1 :
    print ("The line is perpendicular with slope a=infinity and b=0. It represents line x=", x0)
    if y1<y0:
      a=float("-inf")
      b=0
    else:
      a=float("inf")
      b=0
  elif y0 == y1:
  #If both the y-coordinates are zero, then the line is parallel i.e. the line makes an angle of 0 deg with the x-axis.
    print("The line is parallel with slope = 0 and b = y0. It represents y= ", y0)
    a = 0
    b = y0
  else:
    a = np.divide((y1-y0),(x1-x0))
    b = (y1-(a*x1))
  return a,b
  
x0 = float(input("Enter the x-coordinate for first line"))
y0 = float(input("Enter the y-coordinate for first line"))
x1 = float(input("Enter the x-coordinate for second line"))
y1 = float(input("Enter the y-coordinate for second line"))
#Check the coordinates represent line or a point.
if x0 ==x1 and y0 == y1:
  print("This is a point")
else:
  param = param_line(x0,y0,x1,y1)
  print("The slope and intercept for the line is = ",param)



